# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CredifyKitExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CredifyKitExample
	# Crypto
    pod "CredifyCryptoSwift"
    
    # Utility
    pod 'KeychainAccess'
    
    #UI
    pod 'lottie-ios'
    pod 'Kingfisher'
    
    #Network
    pod 'Alamofire', '~> 5.2'

end
